### ISSUE TITLE
Request for an Example Input Data

### ISSUE THREAD

**Issue by PeppaCat** [bryanlimy/CalciumGAN#15]
Hi, Bryan. Thank you for releasing the code of your paper. But I found that the repo does not contain a copy of the reference data to start training. Could you please release an example of training data so that we can know the format of the input data and utilize your model for other research purposes?

**Comment by willgryan** [comment]
I second the above to be able to use and adapt your model. Thank you so much @bryanlimy!

**Comment by bryanlimy** [comment]
Hi @willgryan and @PeppaCat, we will upload the recorded calcium imaging data used in this work upon publication.
